apiVersion: v1
kind: ConfigMap
metadata:
    name: sampleapp-configmap
data:
    PORT: '3000'
    DECORATOR: /api/v1.0

    KEYCLOAK_ADMIN_GRANT_TYPE: password
    KEYCLOAK_ADMIN_CLIENT_ID: admin-cli

    KEYCLOAK_REALM: { { add realm name from keycloak admin ui } }
    KEYCLOAK_CLIENT_ID: { { add client id } }
    KEYCLOAK_CLIENT_GRANT_TYPE: password

    # http://localhost:8080/auth
    KEYCLOAK_SERVER_URL: { { add server url } }
    KEYCLOAK_ISSUER_PATH: realms

    MYSQL_DATABASE: sampleapp-db

    MONGO_HOST: mongodb-standalone-0.mongodb
    MONGO_PORT: '27017'
    MONGO_DB_NAME: sampleapp-db
