apiVersion: v1
kind: Service
metadata:
    name: sampleapp-service
    labels:
        app: sampleapp-service
spec:
    selector:
        app: sampleapp-service
    ports:
        - port: 80
          targetPort: 80
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: sampleapp-service
spec:
    selector:
        matchLabels:
            app: sampleapp-service
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    revisionHistoryLimit: 5
    template:
        metadata:
            name: sampleapp-service
            labels:
                app: sampleapp-service
        spec:
            containers:
                - name: sampleapp-service
                  image: { { image reference } }
                  envFrom:
                      - configMapRef:
                            name: sampleapp-configmap
                      - secretRef:
                            name: sample-secret
                  ports:
                      - containerPort: 80
                  resources:
                      requests:
                          cpu: 25m
