kind: PersistentVolume
apiVersion: v1
metadata:
    name: mongo-pv
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/mnt/mongo_data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        app: mongo-pvc
    name: mongo-pvc
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: manual
    resources:
        requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongodb-standalone
spec:
    serviceName: mongodb
    replicas: 1
    selector:
        matchLabels:
            app: mongodb
    template:
        metadata:
            labels:
                app: mongodb
                selector: mongodb-standalone
        spec:
            containers:
                - name: mongodb-standalone
                  image: mongo:4.0.8
                  volumeMounts:
                      - name: mongo-pvc
                        mountPath: /data/db
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: sampleapp-secret
                                key: MONGO_USERNAME
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: sampleapp-secret
                                key: MONGO_PASSWORD
    volumeClaimTemplates:
        - metadata:
              name: mongo-pvc
          spec:
              accessModes: ['ReadWriteOnce']
              resources:
                  requests:
                      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
    name: mongodb
    labels:
        app: mongodb
spec:
    ports:
        - name: http
          port: 27017
          targetPort: 27017
    clusterIP: None
    selector:
        app: mongodb
    type: ClusterIP
